---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dg86quw872gw/node/
    - /bin/cp server5.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    